spring:
  config:
    activate:
      on-profile: k8s
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
        name: gateway-service
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: rewards-service
          uri: lb://rewards-service
          predicates:
            - Path=/rewards/**
        - id: games-service
          uri: lb://games-service
          predicates:
            - Path=/games/**

  datasource:
    # Points to K8s Service name (mysql-endpoint.yaml)
    url: jdbc:mysql://db-host:3306/gateway_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # Secrets injected by K8s
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
